Repository Nikkei/node-http-helper, pull requests merged in 2023-09, with the labels that each got.

#220 Sort the value of tsconfig's `module` with `moduleResolution` to avoid TS5.2's breaking change
  tsconfig.base.json
Labels: I-enhancement, A-tools

#226 Add `HttpMethodType` type that represents all available http methods
  packages/http-helper/src/mod.ts
Labels: A-feature, I-enhancement

#227 dependabot should watch in-repository composite actions under /.github/actions
  .github/dependabot.yml
Labels: A-ops, I-enhancement
